### ISSUE TITLE
error says zsh not installed on remote server?

### ISSUE THREAD

**Issue by jgroh** [rutchkiwi/copyzshell#6]
I am getting the following error: 

    zsh does not appear to be installed. Your configuration is prepared, so install zsh and then change your shell using chsh -s /bin/zsh, and your configuration should become active.

However zsh is installed on the remote server; when I run `echo $0`, the output is `-zsh`.

**Comment by rutchkiwi** [comment]
Hey!

Not gonna lie, haven't really been using oh-my-zsh for a while now so I can't be 100% sure about the problem. Looking at https://github.com/rutchkiwi/copyzshell/blob/1759f97cb5b4d5b719ada61afd84090533d3c561/copyzshell.zsh#L84 though, that part looks really weird - pretty sure it should be `command -v zsh >/dev/null 2>&1` instead of `command -v zsh1 >/dev/null 2>&1`  (notice the 1). Could you try changing that and re-trying, and let me know if it works?

**Comment by jgroh** [comment]
Yep, that does the trick. I also had to comment out line 88 of `copyzshell.zsh`: `chsh -s /bin/zsh`;  this seemed to cause an error due to not having proper permissions for the command on the remote server.
